# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.AdminCreateIdentityImportCredentialsOidc do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :config
  ]

  @type t :: %__MODULE__{
    :config => OryAPIs.Model.AdminCreateIdentityImportCredentialsOidcConfig.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.AdminCreateIdentityImportCredentialsOidc do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:config, :struct, OryAPIs.Model.AdminCreateIdentityImportCredentialsOidcConfig, options)
  end
end

