# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.AdminCreateIdentityBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :credentials,
    :metadata_admin,
    :metadata_public,
    :recovery_addresses,
    :schema_id,
    :state,
    :traits,
    :verifiable_addresses
  ]

  @type t :: %__MODULE__{
    :credentials => OryAPIs.Model.AdminIdentityImportCredentials.t | nil,
    :metadata_admin => AnyType | nil,
    :metadata_public => AnyType | nil,
    :recovery_addresses => [OryAPIs.Model.RecoveryIdentityAddress.t] | nil,
    :schema_id => String.t,
    :state => OryAPIs.Model.IdentityState.t | nil,
    :traits => map(),
    :verifiable_addresses => [OryAPIs.Model.VerifiableIdentityAddress.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.AdminCreateIdentityBody do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:credentials, :struct, OryAPIs.Model.AdminIdentityImportCredentials, options)
    |> deserialize(:metadata_admin, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:metadata_public, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:recovery_addresses, :list, OryAPIs.Model.RecoveryIdentityAddress, options)
    |> deserialize(:state, :struct, OryAPIs.Model.IdentityState, options)
    |> deserialize(:verifiable_addresses, :list, OryAPIs.Model.VerifiableIdentityAddress, options)
  end
end

