# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.AdminUpdateIdentityBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :credentials,
    :metadata_admin,
    :metadata_public,
    :schema_id,
    :state,
    :traits
  ]

  @type t :: %__MODULE__{
    :credentials => OryAPIs.Model.AdminIdentityImportCredentials.t | nil,
    :metadata_admin => AnyType | nil,
    :metadata_public => AnyType | nil,
    :schema_id => String.t,
    :state => OryAPIs.Model.IdentityState.t,
    :traits => map()
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.AdminUpdateIdentityBody do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:credentials, :struct, OryAPIs.Model.AdminIdentityImportCredentials, options)
    |> deserialize(:metadata_admin, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:metadata_public, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:state, :struct, OryAPIs.Model.IdentityState, options)
  end
end

