# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.ExpandTree do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :children,
    :tuple,
    :type
  ]

  @type t :: %__MODULE__{
    :children => [OryAPIs.Model.ExpandTree.t] | nil,
    :tuple => OryAPIs.Model.RelationTuple.t | nil,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.ExpandTree do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:children, :list, OryAPIs.Model.ExpandTree, options)
    |> deserialize(:tuple, :struct, OryAPIs.Model.RelationTuple, options)
  end
end

