# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.GetRelationTuplesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page_token,
    :relation_tuples
  ]

  @type t :: %__MODULE__{
    :next_page_token => String.t | nil,
    :relation_tuples => [OryAPIs.Model.RelationTuple.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.GetRelationTuplesResponse do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:relation_tuples, :list, OryAPIs.Model.RelationTuple, options)
  end
end

