# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.GetNamespacesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :namespaces
  ]

  @type t :: %__MODULE__{
    :namespaces => [OryAPIs.Model.Namespace.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.GetNamespacesResponse do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:namespaces, :list, OryAPIs.Model.Namespace, options)
  end
end

