# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.IdentityCredentialsPassword do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :hashed_password
  ]

  @type t :: %__MODULE__{
    :hashed_password => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.IdentityCredentialsPassword do
  def decode(value, _options) do
    value
  end
end

