# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.Identity do
  @moduledoc """
  An identity can be a real human, a service, an IoT device - everything that can be described as an \"actor\" in a system.
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :credentials,
    :id,
    :metadata_admin,
    :metadata_public,
    :recovery_addresses,
    :schema_id,
    :schema_url,
    :state,
    :state_changed_at,
    :traits,
    :updated_at,
    :verifiable_addresses
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t | nil,
    :credentials => %{optional(String.t) => OryAPIs.Model.IdentityCredentials.t} | nil,
    :id => String.t,
    :metadata_admin => map() | nil,
    :metadata_public => map() | nil,
    :recovery_addresses => [OryAPIs.Model.RecoveryIdentityAddress.t] | nil,
    :schema_id => String.t,
    :schema_url => String.t,
    :state => OryAPIs.Model.IdentityState.t | nil,
    :state_changed_at => DateTime.t | nil,
    :traits => AnyType | nil,
    :updated_at => DateTime.t | nil,
    :verifiable_addresses => [OryAPIs.Model.VerifiableIdentityAddress.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.Identity do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:credentials, :map, OryAPIs.Model.IdentityCredentials, options)
    |> deserialize(:recovery_addresses, :list, OryAPIs.Model.RecoveryIdentityAddress, options)
    |> deserialize(:state, :struct, OryAPIs.Model.IdentityState, options)
    |> deserialize(:traits, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:verifiable_addresses, :list, OryAPIs.Model.VerifiableIdentityAddress, options)
  end
end

