# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.IdentityCredentialsOidc do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :providers
  ]

  @type t :: %__MODULE__{
    :providers => [OryAPIs.Model.IdentityCredentialsOidcProvider.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.IdentityCredentialsOidc do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:providers, :list, OryAPIs.Model.IdentityCredentialsOidcProvider, options)
  end
end

