# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.IdentitySchemaPreset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :schema,
    :url
  ]

  @type t :: %__MODULE__{
    :schema => map(),
    :url => String.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.IdentitySchemaPreset do
  def decode(value, _options) do
    value
  end
end

