# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.IdentityCredentials do
  @moduledoc """
  Credentials represents a specific credential type
  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :created_at,
    :identifiers,
    :type,
    :updated_at,
    :version
  ]

  @type t :: %__MODULE__{
    :config => map() | nil,
    :created_at => DateTime.t | nil,
    :identifiers => [String.t] | nil,
    :type => OryAPIs.Model.IdentityCredentialsType.t | nil,
    :updated_at => DateTime.t | nil,
    :version => integer() | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.IdentityCredentials do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, OryAPIs.Model.IdentityCredentialsType, options)
  end
end

