# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.JsonWebKeySet do
  @moduledoc """
  JSON Web Key Set
  """

  @derive [Poison.Encoder]
  defstruct [
    :keys
  ]

  @type t :: %__MODULE__{
    :keys => [OryAPIs.Model.JsonWebKey.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.JsonWebKeySet do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:keys, :list, OryAPIs.Model.JsonWebKey, options)
  end
end

