# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.JsonError do
  @moduledoc """
  The standard Ory JSON API error format.
  """

  @derive [Poison.Encoder]
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => OryAPIs.Model.GenericError.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.JsonError do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:error, :struct, OryAPIs.Model.GenericError, options)
  end
end

