# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.LoginRequest do
  @moduledoc """
  LoginRequest struct for LoginRequest
  """

  @derive [Poison.Encoder]
  defstruct [
    :challenge,
    :client,
    :oidc_context,
    :request_url,
    :requested_access_token_audience,
    :requested_scope,
    :session_id,
    :skip,
    :subject
  ]

  @type t :: %__MODULE__{
    :challenge => String.t | nil,
    :client => OryAPIs.Model.OAuth2Client.t | nil,
    :oidc_context => OryAPIs.Model.OpenIdConnectContext.t | nil,
    :request_url => String.t | nil,
    :requested_access_token_audience => [String.t] | nil,
    :requested_scope => [String.t] | nil,
    :session_id => String.t | nil,
    :skip => boolean() | nil,
    :subject => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.LoginRequest do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:client, :struct, OryAPIs.Model.OAuth2Client, options)
    |> deserialize(:oidc_context, :struct, OryAPIs.Model.OpenIdConnectContext, options)
  end
end

