# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.Message do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :body,
    :created_at,
    :id,
    :recipient,
    :send_count,
    :status,
    :subject,
    :template_type,
    :type,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :body => String.t | nil,
    :created_at => DateTime.t | nil,
    :id => String.t | nil,
    :recipient => String.t | nil,
    :send_count => integer() | nil,
    :status => OryAPIs.Model.CourierMessageStatus.t | nil,
    :subject => String.t | nil,
    :template_type => String.t | nil,
    :type => OryAPIs.Model.CourierMessageType.t | nil,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.Message do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:status, :struct, OryAPIs.Model.CourierMessageStatus, options)
    |> deserialize(:type, :struct, OryAPIs.Model.CourierMessageType, options)
  end
end

