# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.OAuth2LogoutRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :challenge,
    :client,
    :request_url,
    :rp_initiated,
    :sid,
    :subject
  ]

  @type t :: %__MODULE__{
    :challenge => String.t | nil,
    :client => OryAPIs.Model.OAuth2Client.t | nil,
    :request_url => String.t | nil,
    :rp_initiated => boolean() | nil,
    :sid => String.t | nil,
    :subject => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.OAuth2LogoutRequest do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:client, :struct, OryAPIs.Model.OAuth2Client, options)
  end
end

