# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.ParseError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :end,
    :message,
    :start
  ]

  @type t :: %__MODULE__{
    :end => OryAPIs.Model.SourcePosition.t | nil,
    :message => String.t | nil,
    :start => OryAPIs.Model.SourcePosition.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.ParseError do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:end, :struct, OryAPIs.Model.SourcePosition, options)
    |> deserialize(:start, :struct, OryAPIs.Model.SourcePosition, options)
  end
end

