# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.PatchDelta do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :relation_tuple
  ]

  @type t :: %__MODULE__{
    :action => String.t | nil,
    :relation_tuple => OryAPIs.Model.RelationTuple.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.PatchDelta do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:relation_tuple, :struct, OryAPIs.Model.RelationTuple, options)
  end
end

