# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.PostCheckOplSyntaxResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
    :errors => [OryAPIs.Model.ParseError.t] | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.PostCheckOplSyntaxResponse do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, OryAPIs.Model.ParseError, options)
  end
end

