# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.ProjectServices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :identity,
    :oauth2,
    :permission
  ]

  @type t :: %__MODULE__{
    :identity => OryAPIs.Model.ProjectServiceIdentity.t | nil,
    :oauth2 => OryAPIs.Model.ProjectServiceOAuth2.t | nil,
    :permission => OryAPIs.Model.ProjectServicePermission.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.ProjectServices do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity, :struct, OryAPIs.Model.ProjectServiceIdentity, options)
    |> deserialize(:oauth2, :struct, OryAPIs.Model.ProjectServiceOAuth2, options)
    |> deserialize(:permission, :struct, OryAPIs.Model.ProjectServicePermission, options)
  end
end

