# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SelfServiceSettingsFlow do
  @moduledoc """
  This flow is used when an identity wants to update settings (e.g. profile data, passwords, ...) in a selfservice manner.  We recommend reading the [User Settings Documentation](../self-service/flows/user-settings)
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :expires_at,
    :id,
    :identity,
    :issued_at,
    :request_url,
    :return_to,
    :state,
    :type,
    :ui
  ]

  @type t :: %__MODULE__{
    :active => String.t | nil,
    :expires_at => DateTime.t,
    :id => String.t,
    :identity => OryAPIs.Model.Identity.t,
    :issued_at => DateTime.t,
    :request_url => String.t,
    :return_to => String.t | nil,
    :state => OryAPIs.Model.SelfServiceSettingsFlowState.t,
    :type => String.t,
    :ui => OryAPIs.Model.UiContainer.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SelfServiceSettingsFlow do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity, :struct, OryAPIs.Model.Identity, options)
    |> deserialize(:state, :struct, OryAPIs.Model.SelfServiceSettingsFlowState, options)
    |> deserialize(:ui, :struct, OryAPIs.Model.UiContainer, options)
  end
end

