# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SelfServiceFlowExpiredError do
  @moduledoc """
  Is sent when a flow is expired
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :debug,
    :details,
    :expired_at,
    :id,
    :message,
    :reason,
    :request,
    :since,
    :status,
    :use_flow_id
  ]

  @type t :: %__MODULE__{
    :code => integer() | nil,
    :debug => String.t | nil,
    :details => %{optional(String.t) => AnyType} | nil,
    :expired_at => DateTime.t | nil,
    :id => String.t | nil,
    :message => String.t,
    :reason => String.t | nil,
    :request => String.t | nil,
    :since => integer() | nil,
    :status => String.t | nil,
    :use_flow_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SelfServiceFlowExpiredError do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:details, :map, OryAPIs.Model.AnyType, options)
  end
end

