# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SelfServiceRegistrationFlow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :expires_at,
    :id,
    :issued_at,
    :oauth2_login_challenge,
    :oauth2_login_request,
    :request_url,
    :return_to,
    :type,
    :ui
  ]

  @type t :: %__MODULE__{
    :active => OryAPIs.Model.IdentityCredentialsType.t | nil,
    :expires_at => DateTime.t,
    :id => String.t,
    :issued_at => DateTime.t,
    :oauth2_login_challenge => String.t | nil,
    :oauth2_login_request => OryAPIs.Model.LoginRequest.t | nil,
    :request_url => String.t,
    :return_to => String.t | nil,
    :type => String.t,
    :ui => OryAPIs.Model.UiContainer.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SelfServiceRegistrationFlow do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:active, :struct, OryAPIs.Model.IdentityCredentialsType, options)
    |> deserialize(:oauth2_login_request, :struct, OryAPIs.Model.LoginRequest, options)
    |> deserialize(:ui, :struct, OryAPIs.Model.UiContainer, options)
  end
end

