# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SelfServiceLoginFlow do
  @moduledoc """
  This object represents a login flow. A login flow is initiated at the \"Initiate Login API / Browser Flow\" endpoint by a client.  Once a login flow is completed successfully, a session cookie or session token will be issued.
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :created_at,
    :expires_at,
    :id,
    :issued_at,
    :oauth2_login_challenge,
    :oauth2_login_request,
    :refresh,
    :request_url,
    :requested_aal,
    :return_to,
    :type,
    :ui,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :active => OryAPIs.Model.IdentityCredentialsType.t | nil,
    :created_at => DateTime.t | nil,
    :expires_at => DateTime.t,
    :id => String.t,
    :issued_at => DateTime.t,
    :oauth2_login_challenge => String.t | nil,
    :oauth2_login_request => OryAPIs.Model.LoginRequest.t | nil,
    :refresh => boolean() | nil,
    :request_url => String.t,
    :requested_aal => OryAPIs.Model.AuthenticatorAssuranceLevel.t | nil,
    :return_to => String.t | nil,
    :type => String.t,
    :ui => OryAPIs.Model.UiContainer.t,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SelfServiceLoginFlow do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:active, :struct, OryAPIs.Model.IdentityCredentialsType, options)
    |> deserialize(:oauth2_login_request, :struct, OryAPIs.Model.LoginRequest, options)
    |> deserialize(:requested_aal, :struct, OryAPIs.Model.AuthenticatorAssuranceLevel, options)
    |> deserialize(:ui, :struct, OryAPIs.Model.UiContainer, options)
  end
end

