# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.Session do
  @moduledoc """
  A Session
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :authenticated_at,
    :authentication_methods,
    :authenticator_assurance_level,
    :devices,
    :expires_at,
    :id,
    :identity,
    :issued_at
  ]

  @type t :: %__MODULE__{
    :active => boolean() | nil,
    :authenticated_at => DateTime.t | nil,
    :authentication_methods => [OryAPIs.Model.SessionAuthenticationMethod.t] | nil,
    :authenticator_assurance_level => OryAPIs.Model.AuthenticatorAssuranceLevel.t | nil,
    :devices => [OryAPIs.Model.SessionDevice.t] | nil,
    :expires_at => DateTime.t | nil,
    :id => String.t,
    :identity => OryAPIs.Model.Identity.t,
    :issued_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.Session do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:authentication_methods, :list, OryAPIs.Model.SessionAuthenticationMethod, options)
    |> deserialize(:authenticator_assurance_level, :struct, OryAPIs.Model.AuthenticatorAssuranceLevel, options)
    |> deserialize(:devices, :list, OryAPIs.Model.SessionDevice, options)
    |> deserialize(:identity, :struct, OryAPIs.Model.Identity, options)
  end
end

