# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SessionAuthenticationMethod do
  @moduledoc """
  A singular authenticator used during authentication / login.
  """

  @derive [Poison.Encoder]
  defstruct [
    :aal,
    :completed_at,
    :method
  ]

  @type t :: %__MODULE__{
    :aal => OryAPIs.Model.AuthenticatorAssuranceLevel.t | nil,
    :completed_at => DateTime.t | nil,
    :method => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SessionAuthenticationMethod do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:aal, :struct, OryAPIs.Model.AuthenticatorAssuranceLevel, options)
  end
end

