# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SuccessfulProjectUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project,
    :warnings
  ]

  @type t :: %__MODULE__{
    :project => OryAPIs.Model.Project.t,
    :warnings => [OryAPIs.Model.Warning.t]
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SuccessfulProjectUpdate do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:project, :struct, OryAPIs.Model.Project, options)
    |> deserialize(:warnings, :list, OryAPIs.Model.Warning, options)
  end
end

