# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.SuccessfulSelfServiceRegistrationWithoutBrowser do
  @moduledoc """
  The Response for Registration Flows via API
  """

  @derive [Poison.Encoder]
  defstruct [
    :identity,
    :session,
    :session_token
  ]

  @type t :: %__MODULE__{
    :identity => OryAPIs.Model.Identity.t,
    :session => OryAPIs.Model.Session.t | nil,
    :session_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.SuccessfulSelfServiceRegistrationWithoutBrowser do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity, :struct, OryAPIs.Model.Identity, options)
    |> deserialize(:session, :struct, OryAPIs.Model.Session, options)
  end
end

