# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiContainer do
  @moduledoc """
  Container represents a HTML Form. The container can work with both HTTP Form and JSON requests
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :messages,
    :method,
    :nodes
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :messages => [OryAPIs.Model.UiText.t] | nil,
    :method => String.t,
    :nodes => [OryAPIs.Model.UiNode.t]
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiContainer do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:messages, :list, OryAPIs.Model.UiText, options)
    |> deserialize(:nodes, :list, OryAPIs.Model.UiNode, options)
  end
end

