# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiNodeAttributes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :autocomplete,
    :disabled,
    :label,
    :name,
    :node_type,
    :onclick,
    :pattern,
    :required,
    :type,
    :value,
    :id,
    :text,
    :height,
    :src,
    :width,
    :href,
    :title,
    :async,
    :crossorigin,
    :integrity,
    :nonce,
    :referrerpolicy
  ]

  @type t :: %__MODULE__{
    :autocomplete => String.t | nil,
    :disabled => boolean(),
    :label => OryAPIs.Model.UiText.t | nil,
    :name => String.t,
    :node_type => String.t,
    :onclick => String.t | nil,
    :pattern => String.t | nil,
    :required => boolean() | nil,
    :type => String.t,
    :value => AnyType | nil,
    :id => String.t,
    :text => OryAPIs.Model.UiText.t,
    :height => integer(),
    :src => String.t,
    :width => integer(),
    :href => String.t,
    :title => OryAPIs.Model.UiText.t,
    :async => boolean(),
    :crossorigin => String.t,
    :integrity => String.t,
    :nonce => String.t,
    :referrerpolicy => String.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiNodeAttributes do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:label, :struct, OryAPIs.Model.UiText, options)
    |> deserialize(:value, :struct, OryAPIs.Model.AnyType, options)
    |> deserialize(:text, :struct, OryAPIs.Model.UiText, options)
    |> deserialize(:title, :struct, OryAPIs.Model.UiText, options)
  end
end

