# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiNode do
  @moduledoc """
  Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :attributes,
    :group,
    :messages,
    :meta,
    :type
  ]

  @type t :: %__MODULE__{
    :attributes => OryAPIs.Model.UiNodeAttributes.t,
    :group => String.t,
    :messages => [OryAPIs.Model.UiText.t],
    :meta => OryAPIs.Model.UiNodeMeta.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiNode do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attributes, :struct, OryAPIs.Model.UiNodeAttributes, options)
    |> deserialize(:messages, :list, OryAPIs.Model.UiText, options)
    |> deserialize(:meta, :struct, OryAPIs.Model.UiNodeMeta, options)
  end
end

