# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiNodeMeta do
  @moduledoc """
  This might include a label and other information that can optionally be used to render UIs.
  """

  @derive [Poison.Encoder]
  defstruct [
    :label
  ]

  @type t :: %__MODULE__{
    :label => OryAPIs.Model.UiText.t | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiNodeMeta do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:label, :struct, OryAPIs.Model.UiText, options)
  end
end

