# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiNodeInputAttributes do
  @moduledoc """
  InputAttributes represents the attributes of an input node
  """

  @derive [Poison.Encoder]
  defstruct [
    :autocomplete,
    :disabled,
    :label,
    :name,
    :node_type,
    :onclick,
    :pattern,
    :required,
    :type,
    :value
  ]

  @type t :: %__MODULE__{
    :autocomplete => String.t | nil,
    :disabled => boolean(),
    :label => OryAPIs.Model.UiText.t | nil,
    :name => String.t,
    :node_type => String.t,
    :onclick => String.t | nil,
    :pattern => String.t | nil,
    :required => boolean() | nil,
    :type => String.t,
    :value => AnyType | nil
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiNodeInputAttributes do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:label, :struct, OryAPIs.Model.UiText, options)
    |> deserialize(:value, :struct, OryAPIs.Model.AnyType, options)
  end
end

