# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UiNodeAnchorAttributes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :href,
    :id,
    :node_type,
    :title
  ]

  @type t :: %__MODULE__{
    :href => String.t,
    :id => String.t,
    :node_type => String.t,
    :title => OryAPIs.Model.UiText.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UiNodeAnchorAttributes do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:title, :struct, OryAPIs.Model.UiText, options)
  end
end

