# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Model.UpdateProject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :services
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :services => OryAPIs.Model.ProjectServices.t
  }
end

defimpl Poison.Decoder, for: OryAPIs.Model.UpdateProject do
  import OryAPIs.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:services, :struct, OryAPIs.Model.ProjectServices, options)
  end
end

