/*
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: v0.3.0
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.api;

import sh.ory.ApiException;
import sh.ory.model.JsonError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IdentityApi
 */
@Disabled
public class IdentityApiTest {

    private final IdentityApi api = new IdentityApi();

    /**
     * Deactivate a Session
     *
     * Calling this endpoint deactivates the specified session. Session data is not deleted.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void disableSessionTest() throws ApiException {
        String id = null;
        api.disableSession(id);
        // TODO: test validations
    }

}
