# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.CreateJsonWebKeySet do
  @moduledoc """
  Create JSON Web Key Set Request Body
  """

  @derive [Poison.Encoder]
  defstruct [
    :alg,
    :kid,
    :use
  ]

  @type t :: %__MODULE__{
    :alg => String.t,
    :kid => String.t,
    :use => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.CreateJsonWebKeySet do
  def decode(value, _options) do
    value
  end
end

