# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.JsonPatch do
  @moduledoc """
  A JSONPatch document as defined by RFC 6902
  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :op,
    :path,
    :value
  ]

  @type t :: %__MODULE__{
    :from => String.t | nil,
    :op => String.t,
    :path => String.t,
    :value => any | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.JsonPatch do
  import Ory.Hydra.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:value, :any, :any, options)
  end
end

