# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.JsonWebKeySet do
  @moduledoc """
  JSON Web Key Set
  """

  @derive [Poison.Encoder]
  defstruct [
    :keys
  ]

  @type t :: %__MODULE__{
    :keys => [Ory.Hydra.Model.JsonWebKey.t] | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.JsonWebKeySet do
  import Ory.Hydra.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:keys, :list, Ory.Hydra.Model.JsonWebKey, options)
  end
end

