# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Ory.Hydra.Model.JsonPatch do
  @moduledoc """
  A JSONPatch document as defined by RFC 6902
  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :op,
    :path,
    :value
  ]

  @type t :: %__MODULE__{
    :from => String.t | nil,
    :op => String.t,
    :path => String.t,
    :value => AnyType | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.JsonPatch do
  import Ory.Hydra.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:value, :struct, Ory.Hydra.Model.AnyType, options)
  end
end

