# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.OAuth2LogoutRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :challenge,
    :client,
    :request_url,
    :rp_initiated,
    :sid,
    :subject
  ]

  @type t :: %__MODULE__{
    :challenge => String.t | nil,
    :client => Ory.Hydra.Model.OAuth2Client.t | nil,
    :request_url => String.t | nil,
    :rp_initiated => boolean() | nil,
    :sid => String.t | nil,
    :subject => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.OAuth2LogoutRequest do
  import Ory.Hydra.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:client, :struct, Ory.Hydra.Model.OAuth2Client, options)
  end
end

