# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.Pagination do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :page_size,
    :page_token
  ]

  @type t :: %__MODULE__{
    :page_size => integer() | nil,
    :page_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.Pagination do
  def decode(value, _options) do
    value
  end
end

