# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.TokenPaginationHeaders do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :link,
    :"x-total-count"
  ]

  @type t :: %__MODULE__{
    :link => String.t | nil,
    :"x-total-count" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.TokenPaginationHeaders do
  def decode(value, _options) do
    value
  end
end

