# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.TokenPaginationResponseHeaders do
  @moduledoc """
  The `Link` HTTP header contains multiple links (`first`, `next`, `last`, `previous`) formatted as: `<https://{project-slug}.projects.oryapis.com/admin/clients?page_size={limit}&page_token={offset}>; rel=\"{page}\"`  For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination).
  """

  @derive [Poison.Encoder]
  defstruct [
    :link,
    :"x-total-count"
  ]

  @type t :: %__MODULE__{
    :link => String.t | nil,
    :"x-total-count" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.TokenPaginationResponseHeaders do
  def decode(value, _options) do
    value
  end
end

