# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Model.TrustedOAuth2JwtGrantJsonWebKey do
  @moduledoc """
  OAuth2 JWT Bearer Grant Type Issuer Trusted JSON Web Key
  """

  @derive [Poison.Encoder]
  defstruct [
    :kid,
    :set
  ]

  @type t :: %__MODULE__{
    :kid => String.t | nil,
    :set => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Hydra.Model.TrustedOAuth2JwtGrantJsonWebKey do
  def decode(value, _options) do
    value
  end
end

