# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Ory.Kratos.Model.AdminUpdateIdentityBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :metadata_admin,
    :metadata_public,
    :schema_id,
    :state,
    :traits
  ]

  @type t :: %__MODULE__{
    :metadata_admin => AnyType | nil,
    :metadata_public => AnyType | nil,
    :schema_id => String.t,
    :state => Ory.Kratos.Model.IdentityState.t,
    :traits => map()
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminUpdateIdentityBody do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:metadata_admin, :struct, Ory.Kratos.Model.AnyType, options)
    |> deserialize(:metadata_public, :struct, Ory.Kratos.Model.AnyType, options)
    |> deserialize(:state, :struct, Ory.Kratos.Model.IdentityState, options)
  end
end

