# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.AdminCreateSelfServiceRecoveryLinkBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :expires_in,
    :identity_id
  ]

  @type t :: %__MODULE__{
    :expires_in => String.t | nil,
    :identity_id => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminCreateSelfServiceRecoveryLinkBody do
  def decode(value, _options) do
    value
  end
end

