# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Ory.Kratos.Model.AdminIdentityImportCredentials do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :oidc,
    :password
  ]

  @type t :: %__MODULE__{
    :oidc => Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidc.t | nil,
    :password => Ory.Kratos.Model.AdminCreateIdentityImportCredentialsPassword.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminIdentityImportCredentials do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:oidc, :struct, Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidc, options)
    |> deserialize(:password, :struct, Ory.Kratos.Model.AdminCreateIdentityImportCredentialsPassword, options)
  end
end

