# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.AdminUpdateIdentityBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :metadata_admin,
    :metadata_public,
    :schema_id,
    :state,
    :traits
  ]

  @type t :: %__MODULE__{
    :metadata_admin => any() | nil,
    :metadata_public => any() | nil,
    :schema_id => String.t,
    :state => Ory.Kratos.Model.IdentityState.t,
    :traits => map()
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminUpdateIdentityBody do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:metadata_admin, :any, :any, options)
    |> deserialize(:metadata_public, :any, :any, options)
    |> deserialize(:state, :struct, Ory.Kratos.Model.IdentityState, options)
  end
end

