# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidc do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :config
  ]

  @type t :: %__MODULE__{
    :config => Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcConfig.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidc do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:config, :struct, Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcConfig, options)
  end
end

