# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :providers
  ]

  @type t :: %__MODULE__{
    :config => Ory.Kratos.Model.AdminCreateIdentityImportCredentialsPasswordConfig.t | nil,
    :providers => [Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcProvider.t] | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcConfig do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:config, :struct, Ory.Kratos.Model.AdminCreateIdentityImportCredentialsPasswordConfig, options)
    |> deserialize(:providers, :list, Ory.Kratos.Model.AdminCreateIdentityImportCredentialsOidcProvider, options)
  end
end

