# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.IdentityCredentials do
  @moduledoc """
  Credentials represents a specific credential type
  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :created_at,
    :identifiers,
    :type,
    :updated_at,
    :version
  ]

  @type t :: %__MODULE__{
    :config => map() | nil,
    :created_at => DateTime.t | nil,
    :identifiers => [String.t] | nil,
    :type => Ory.Kratos.Model.IdentityCredentialsType.t | nil,
    :updated_at => DateTime.t | nil,
    :version => integer() | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.IdentityCredentials do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, Ory.Kratos.Model.IdentityCredentialsType, options)
  end
end

