# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.IdentityCredentialsPassword do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :hashed_password
  ]

  @type t :: %__MODULE__{
    :hashed_password => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.IdentityCredentialsPassword do
  def decode(value, _options) do
    value
  end
end

