# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.IdentityState do
  @moduledoc """
  The state can either be `active` or `inactive`.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.IdentityState do
  def decode(value, _options) do
    value
  end
end

