# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.RecoveryAddress do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :id,
    :updated_at,
    :value,
    :via
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t | nil,
    :id => String.t,
    :updated_at => DateTime.t | nil,
    :value => String.t,
    :via => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.RecoveryAddress do
  def decode(value, _options) do
    value
  end
end

