# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SelfServiceFlowExpiredError do
  @moduledoc """
  Is sent when a flow is expired
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :debug,
    :details,
    :id,
    :message,
    :reason,
    :request,
    :since,
    :status,
    :use_flow_id
  ]

  @type t :: %__MODULE__{
    :code => integer() | nil,
    :debug => String.t | nil,
    :details => %{optional(String.t) => AnyType} | nil,
    :id => String.t | nil,
    :message => String.t,
    :reason => String.t | nil,
    :request => String.t | nil,
    :since => integer() | nil,
    :status => String.t | nil,
    :use_flow_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceFlowExpiredError do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:details, :map, Ory.Kratos.Model.AnyType, options)
  end
end

