# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SelfServiceError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :error,
    :id,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t | nil,
    :error => map() | nil,
    :id => String.t,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceError do
  def decode(value, _options) do
    value
  end
end

