# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SelfServiceSettingsFlow do
  @moduledoc """
  This flow is used when an identity wants to update settings (e.g. profile data, passwords, ...) in a selfservice manner.  We recommend reading the [User Settings Documentation](../self-service/flows/user-settings)
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :expires_at,
    :id,
    :identity,
    :issued_at,
    :request_url,
    :return_to,
    :state,
    :type,
    :ui
  ]

  @type t :: %__MODULE__{
    :active => String.t | nil,
    :expires_at => DateTime.t,
    :id => String.t,
    :identity => Ory.Kratos.Model.Identity.t,
    :issued_at => DateTime.t,
    :request_url => String.t,
    :return_to => String.t | nil,
    :state => Ory.Kratos.Model.SelfServiceSettingsFlowState.t,
    :type => String.t,
    :ui => Ory.Kratos.Model.UiContainer.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceSettingsFlow do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity, :struct, Ory.Kratos.Model.Identity, options)
    |> deserialize(:state, :struct, Ory.Kratos.Model.SelfServiceSettingsFlowState, options)
    |> deserialize(:ui, :struct, Ory.Kratos.Model.UiContainer, options)
  end
end

