# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SelfServiceLogoutUrl do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :logout_token,
    :logout_url
  ]

  @type t :: %__MODULE__{
    :logout_token => String.t,
    :logout_url => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceLogoutUrl do
  def decode(value, _options) do
    value
  end
end

