# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SelfServiceRecoveryLink do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :expires_at,
    :recovery_link
  ]

  @type t :: %__MODULE__{
    :expires_at => DateTime.t | nil,
    :recovery_link => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceRecoveryLink do
  def decode(value, _options) do
    value
  end
end

