# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Ory.Kratos.Model.SelfServiceRegistrationFlow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :expires_at,
    :id,
    :issued_at,
    :request_url,
    :return_to,
    :type,
    :ui
  ]

  @type t :: %__MODULE__{
    :active => Ory.Kratos.Model.IdentityCredentialsType.t | nil,
    :expires_at => DateTime.t,
    :id => String.t,
    :issued_at => DateTime.t,
    :request_url => String.t,
    :return_to => String.t | nil,
    :type => String.t,
    :ui => Ory.Kratos.Model.UiContainer.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SelfServiceRegistrationFlow do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:active, :struct, Ory.Kratos.Model.IdentityCredentialsType, options)
    |> deserialize(:ui, :struct, Ory.Kratos.Model.UiContainer, options)
  end
end

