# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SettingsProfileFormConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :messages,
    :method,
    :nodes
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :messages => [Ory.Kratos.Model.UiText.t] | nil,
    :method => String.t,
    :nodes => [Ory.Kratos.Model.UiNode.t]
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SettingsProfileFormConfig do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:messages, :list, Ory.Kratos.Model.UiText, options)
    |> deserialize(:nodes, :list, Ory.Kratos.Model.UiNode, options)
  end
end

