# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceLoginFlowWithOidcMethodBody do
  @moduledoc """
  SubmitSelfServiceLoginFlowWithOidcMethodBody is used to decode the login form payload when using the oidc method.
  """

  @derive [Poison.Encoder]
  defstruct [
    :csrf_token,
    :method,
    :provider,
    :traits
  ]

  @type t :: %__MODULE__{
    :csrf_token => String.t | nil,
    :method => String.t,
    :provider => String.t,
    :traits => map() | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceLoginFlowWithOidcMethodBody do
  def decode(value, _options) do
    value
  end
end

