# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceLoginFlowWithTotpMethodBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :csrf_token,
    :method,
    :totp_code
  ]

  @type t :: %__MODULE__{
    :csrf_token => String.t | nil,
    :method => String.t,
    :totp_code => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceLoginFlowWithTotpMethodBody do
  def decode(value, _options) do
    value
  end
end

