# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceSettingsFlowWithProfileMethodBody do
  @moduledoc """
  nolint:deadcode,unused
  """

  @derive [Poison.Encoder]
  defstruct [
    :csrf_token,
    :method,
    :traits
  ]

  @type t :: %__MODULE__{
    :csrf_token => String.t | nil,
    :method => String.t,
    :traits => map()
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceSettingsFlowWithProfileMethodBody do
  def decode(value, _options) do
    value
  end
end

