# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceSettingsFlowWithOidcMethodBody do
  @moduledoc """
  nolint:deadcode,unused
  """

  @derive [Poison.Encoder]
  defstruct [
    :flow,
    :link,
    :method,
    :traits,
    :unlink
  ]

  @type t :: %__MODULE__{
    :flow => String.t | nil,
    :link => String.t | nil,
    :method => String.t,
    :traits => map() | nil,
    :unlink => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceSettingsFlowWithOidcMethodBody do
  def decode(value, _options) do
    value
  end
end

