# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceLogoutFlowWithoutBrowserBody do
  @moduledoc """
  nolint:deadcode,unused
  """

  @derive [Poison.Encoder]
  defstruct [
    :session_token
  ]

  @type t :: %__MODULE__{
    :session_token => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceLogoutFlowWithoutBrowserBody do
  def decode(value, _options) do
    value
  end
end

