# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SubmitSelfServiceRegistrationFlowWithWebAuthnMethodBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :csrf_token,
    :method,
    :traits,
    :webauthn_register,
    :webauthn_register_displayname
  ]

  @type t :: %__MODULE__{
    :csrf_token => String.t | nil,
    :method => String.t,
    :traits => map(),
    :webauthn_register => String.t | nil,
    :webauthn_register_displayname => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SubmitSelfServiceRegistrationFlowWithWebAuthnMethodBody do
  def decode(value, _options) do
    value
  end
end

