# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.SuccessfulSelfServiceRegistrationWithoutBrowser do
  @moduledoc """
  The Response for Registration Flows via API
  """

  @derive [Poison.Encoder]
  defstruct [
    :identity,
    :session,
    :session_token
  ]

  @type t :: %__MODULE__{
    :identity => Ory.Kratos.Model.Identity.t,
    :session => Ory.Kratos.Model.Session.t | nil,
    :session_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.SuccessfulSelfServiceRegistrationWithoutBrowser do
  import Ory.Kratos.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity, :struct, Ory.Kratos.Model.Identity, options)
    |> deserialize(:session, :struct, Ory.Kratos.Model.Session, options)
  end
end

