# NOTE: This file is auto generated by OpenAPI Generator 6.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Kratos.Model.UiText do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :context,
    :id,
    :text,
    :type
  ]

  @type t :: %__MODULE__{
    :context => map() | nil,
    :id => integer(),
    :text => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: Ory.Kratos.Model.UiText do
  def decode(value, _options) do
    value
  end
end

