# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Api.Identity do
  @moduledoc """
  API calls for all endpoints tagged `Identity`.
  """

  alias OryAPIs.Connection
  import OryAPIs.RequestBuilder


  @doc """
  Deactivate a Session
  Calling this endpoint deactivates the specified session. Session data is not deleted.

  ## Parameters

  - connection (OryAPIs.Connection): Connection to server
  - id (String.t): ID is the session's ID.
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec disable_session(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, OryAPIs.Model.JsonError.t} | {:error, Tesla.Env.t}
  def disable_session(connection, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/admin/sessions/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 204, false},
      { 400, %OryAPIs.Model.JsonError{}},
      { 401, %OryAPIs.Model.JsonError{}},
      { :default, %OryAPIs.Model.JsonError{}}
    ])
  end
end
