# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Api.Namespaces do
  @moduledoc """
  API calls for all endpoints tagged `Namespaces`.
  """

  alias OryAPIs.Connection
  import OryAPIs.RequestBuilder


  @doc """
  Query namespaces
  Get all namespaces

  ## Parameters

  - connection (OryAPIs.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, OryAPIs.Model.GetNamespacesResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_namespaces(Tesla.Env.client, keyword()) :: {:ok, OryAPIs.Model.GenericError.t} | {:ok, OryAPIs.Model.GetNamespacesResponse.t} | {:error, Tesla.Env.t}
  def get_namespaces(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/namespaces")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %OryAPIs.Model.GetNamespacesResponse{}},
      { 500, %OryAPIs.Model.GenericError{}}
    ])
  end
end
