# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OryAPIs.Api.Wellknown do
  @moduledoc """
  API calls for all endpoints tagged `Wellknown`.
  """

  alias OryAPIs.Connection
  import OryAPIs.RequestBuilder


  @doc """
  Discover Well-Known JSON Web Keys
  This endpoint returns JSON Web Keys required to verifying OpenID Connect ID Tokens and, if enabled, OAuth 2.0 JWT Access Tokens. This endpoint can be used with client libraries like [node-jwks-rsa](https://github.com/auth0/node-jwks-rsa) among others.

  ## Parameters

  - connection (OryAPIs.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, OryAPIs.Model.JsonWebKeySet.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec discover_json_web_keys(Tesla.Env.client, keyword()) :: {:ok, OryAPIs.Model.ErrorOAuth2.t} | {:ok, OryAPIs.Model.JsonWebKeySet.t} | {:error, Tesla.Env.t}
  def discover_json_web_keys(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/.well-known/jwks.json")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %OryAPIs.Model.JsonWebKeySet{}},
      { :default, %OryAPIs.Model.ErrorOAuth2{}}
    ])
  end
end
