# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Hydra.Api.Wellknown do
  @moduledoc """
  API calls for all endpoints tagged `Wellknown`.
  """

  alias Ory.Hydra.Connection
  import Ory.Hydra.RequestBuilder

  @doc """
  Discover Well-Known JSON Web Keys
  This endpoint returns JSON Web Keys required to verifying OpenID Connect ID Tokens and, if enabled, OAuth 2.0 JWT Access Tokens. This endpoint can be used with client libraries like [node-jwks-rsa](https://github.com/auth0/node-jwks-rsa) among others.

  ### Parameters

  - `connection` (Ory.Hydra.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Ory.Hydra.Model.JsonWebKeySet.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec discover_json_web_keys(Tesla.Env.client, keyword()) :: {:ok, Ory.Hydra.Model.JsonWebKeySet.t} | {:ok, Ory.Hydra.Model.ErrorOAuth2.t} | {:error, Tesla.Env.t}
  def discover_json_web_keys(connection, _opts \\ []) do
    request =
      %Tesla.Env{
        method: :get,
        url: "/.well-known/jwks.json",
      }
      |> Map.from_struct()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %Ory.Hydra.Model.JsonWebKeySet{}},
      {:default, %Ory.Hydra.Model.ErrorOAuth2{}}
    ])
  end
end
