/*
 * Ory Kratos API
 * Documentation for all public and administrative Ory Kratos APIs. Public and administrative APIs are exposed on different ports. Public APIs can face the public internet without any protection while administrative APIs should never be exposed without prior authorization. To protect the administative API port you should use something like Nginx, Ory Oathkeeper, or any other technology capable of authorizing incoming requests. 
 *
 * The version of the OpenAPI document: v0.10.1
 * Contact: hi@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.kratos;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
                .registerTypeSelector(sh.ory.kratos.model.SubmitSelfServiceLoginFlowBody.class, new TypeSelector<sh.ory.kratos.model.SubmitSelfServiceLoginFlowBody>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.SubmitSelfServiceLoginFlowBody> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("lookup_secret", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithLookupSecretMethodBody.class);
                        classByDiscriminatorValue.put("oidc", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("password", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowWithLookupSecretMethodBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithLookupSecretMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowWithOidcMethodBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowWithPasswordMethodBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowWithTotpMethodBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithTotpMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowWithWebAuthnMethodBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("totp", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithTotpMethodBody.class);
                        classByDiscriminatorValue.put("webauthn", sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceLoginFlowBody", sh.ory.kratos.model.SubmitSelfServiceLoginFlowBody.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "method"));
                    }
          })
                .registerTypeSelector(sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowBody.class, new TypeSelector<sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowBody>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowBody> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("link", sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowWithLinkMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRecoveryFlowWithLinkMethodBody", sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowWithLinkMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRecoveryFlowBody", sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowBody.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "method"));
                    }
          })
                .registerTypeSelector(sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowBody.class, new TypeSelector<sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowBody>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowBody> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("oidc", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("password", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRegistrationFlowWithOidcMethodBody", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRegistrationFlowWithPasswordMethodBody", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRegistrationFlowWithWebAuthnMethodBody", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("webauthn", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceRegistrationFlowBody", sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowBody.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "method"));
                    }
          })
                .registerTypeSelector(sh.ory.kratos.model.SubmitSelfServiceSettingsFlowBody.class, new TypeSelector<sh.ory.kratos.model.SubmitSelfServiceSettingsFlowBody>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.SubmitSelfServiceSettingsFlowBody> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("lookup_secret", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithLookupMethodBody.class);
                        classByDiscriminatorValue.put("oidc", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("password", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("profile", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithProfileMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithLookupMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithLookupMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithOidcMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithOidcMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithPasswordMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithPasswordMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithProfileMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithProfileMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithTotpMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithTotpMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowWithWebAuthnMethodBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("totp", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithTotpMethodBody.class);
                        classByDiscriminatorValue.put("webauthn", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithWebAuthnMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceSettingsFlowBody", sh.ory.kratos.model.SubmitSelfServiceSettingsFlowBody.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "method"));
                    }
          })
                .registerTypeSelector(sh.ory.kratos.model.SubmitSelfServiceVerificationFlowBody.class, new TypeSelector<sh.ory.kratos.model.SubmitSelfServiceVerificationFlowBody>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.SubmitSelfServiceVerificationFlowBody> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("link", sh.ory.kratos.model.SubmitSelfServiceVerificationFlowWithLinkMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceVerificationFlowWithLinkMethodBody", sh.ory.kratos.model.SubmitSelfServiceVerificationFlowWithLinkMethodBody.class);
                        classByDiscriminatorValue.put("submitSelfServiceVerificationFlowBody", sh.ory.kratos.model.SubmitSelfServiceVerificationFlowBody.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "method"));
                    }
          })
                .registerTypeSelector(sh.ory.kratos.model.UiNodeAttributes.class, new TypeSelector<sh.ory.kratos.model.UiNodeAttributes>() {
                    @Override
                    public Class<? extends sh.ory.kratos.model.UiNodeAttributes> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("a", sh.ory.kratos.model.UiNodeAnchorAttributes.class);
                        classByDiscriminatorValue.put("img", sh.ory.kratos.model.UiNodeImageAttributes.class);
                        classByDiscriminatorValue.put("input", sh.ory.kratos.model.UiNodeInputAttributes.class);
                        classByDiscriminatorValue.put("script", sh.ory.kratos.model.UiNodeScriptAttributes.class);
                        classByDiscriminatorValue.put("text", sh.ory.kratos.model.UiNodeTextAttributes.class);
                        classByDiscriminatorValue.put("uiNodeAnchorAttributes", sh.ory.kratos.model.UiNodeAnchorAttributes.class);
                        classByDiscriminatorValue.put("uiNodeImageAttributes", sh.ory.kratos.model.UiNodeImageAttributes.class);
                        classByDiscriminatorValue.put("uiNodeInputAttributes", sh.ory.kratos.model.UiNodeInputAttributes.class);
                        classByDiscriminatorValue.put("uiNodeScriptAttributes", sh.ory.kratos.model.UiNodeScriptAttributes.class);
                        classByDiscriminatorValue.put("uiNodeTextAttributes", sh.ory.kratos.model.UiNodeTextAttributes.class);
                        classByDiscriminatorValue.put("uiNodeAttributes", sh.ory.kratos.model.UiNodeAttributes.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "node_type"));
                    }
          })
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityImportCredentialsOidc.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityImportCredentialsOidcConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityImportCredentialsOidcProvider.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityImportCredentialsPassword.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateIdentityImportCredentialsPasswordConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminCreateSelfServiceRecoveryLinkBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminIdentityImportCredentials.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.AdminUpdateIdentityBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.ErrorAuthenticatorAssuranceLevelNotSatisfied.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.GenericError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.GetVersion200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.HealthNotReadyStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.HealthStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.Identity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IdentityCredentials.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IdentityCredentialsOidc.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IdentityCredentialsOidcProvider.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IdentityCredentialsPassword.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IdentitySchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IsAlive200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.IsReady503Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.JsonError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.NeedsPrivilegedSessionError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.Pagination.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.RecoveryAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.RevokedSessions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceBrowserLocationChangeRequiredError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceFlowExpiredError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceLoginFlow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceLogoutUrl.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceRecoveryFlow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceRecoveryLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceRegistrationFlow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceSettingsFlow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SelfServiceVerificationFlow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.Session.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SessionAuthenticationMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SessionDevice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SettingsProfileFormConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceFlowWithWebAuthnRegistrationMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithLookupSecretMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithOidcMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithPasswordMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithTotpMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLoginFlowWithWebAuthnMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceLogoutFlowWithoutBrowserBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRecoveryFlowWithLinkMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithOidcMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithPasswordMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceRegistrationFlowWithWebAuthnMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithLookupMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithOidcMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithPasswordMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithProfileMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithTotpMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceSettingsFlowWithWebAuthnMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceVerificationFlowBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SubmitSelfServiceVerificationFlowWithLinkMethodBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SuccessfulSelfServiceLoginWithoutBrowser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.SuccessfulSelfServiceRegistrationWithoutBrowser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiContainer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNode.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeAnchorAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeImageAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeInputAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeScriptAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiNodeTextAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.UiText.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.VerifiableIdentityAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new sh.ory.kratos.model.Version.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
